### ISSUE TITLE
VT (8204) support in the code

### ISSUE THREAD

**Issue by Durgababu** [go-ole/go-ole#117]
VT (8204) support in the code:

getProperty(src,n) returing the following value

&{VT(8204) 0 0 0 2703200 [0 0 0 0 0 0 0 0]}

actually it is string array type. 

Varaint.Value() is not supporting this case.

How to read property value from the above output

**Comment by mattn** [comment]
Property is a feature of IDispatch. So you need to convert it into IDispatch using `ToIDispatch()`.

**Comment by Durgababu** [comment]
Hi mattn,

Thanks for your quick response.

But my requirement is like below,

i am using Win32_BIOS,  in that i need BIOSVersion property value, there it is string[] 

how can i retrieve this BIOSVersion?

**Comment by mattn** [comment]
@Durgababu try last change.
```go
package main

import (
	"fmt"
	"github.com/go-ole/go-ole"
	"github.com/go-ole/go-ole/oleutil"
	"log"
)

func main() {
	ole.CoInitialize(0)
	unk, err := oleutil.CreateObject("WbemScripting.SWbemLocator")
	if err != nil {
		log.Fatal(err)
	}
	loader := unk.MustQueryInterface(ole.IID_IDispatch)

	service := oleutil.MustCallMethod(loader, "ConnectServer").ToIDispatch()
	classset := oleutil.MustCallMethod(service, "ExecQuery", "Select * From Win32_BIOS").ToIDispatch()
	enum, _ := oleutil.MustGetProperty(classset, "_NewEnum").ToIUnknown().IEnumVARIANT(ole.IID_IEnumVariant)
	for {
		item, _, err := enum.Next(1)
		if err != nil {
			break
		}
		obj := item.ToIDispatch()
		vers := oleutil.MustGetProperty(obj, "BIOSVersion").ToArray().ToValueArray()
		for _, v := range vers {
			fmt.Println(v)
		}
	}
}
```

**Comment by Durgababu** [comment]
Hi Mattn, 

i am getting the following error while trying the above program.

# command-line-arguments
.\biosWMI.go:27: oleutil.MustGetProperty(obj, "BIOSVersion").ToArray().ToValueArray undefined (type *ole.SafeArrayConversion has no field or method ToValueArray)

**Comment by mattn** [comment]
did you pull latest?

On 1/11/16, Durgababu <notifications@github.com> wrote:
> Hi Mattn,
>
> i am getting the following error while trying the above program.
>
> # command-line-arguments
> .\biosWMI.go:27: oleutil.MustGetProperty(obj,
> "BIOSVersion").ToArray().ToValueArray undefined (type
> *ole.SafeArrayConversion has no field or method ToValueArray)
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/go-ole/go-ole/issues/117#issuecomment-170444934


-- 
- Yasuhiro Matsumoto

**Comment by Durgababu** [comment]
did you pull latest?

means? 
sorry i didn't get you

**Comment by Durgababu** [comment]
Hi Mattn,

I am waiting for your response.  :-)

**Comment by Durgababu** [comment]
Thanks a lot Mattn

its working after pulling latest one.
