### ISSUE TITLE
How to Invoke an ActiveX 32Bits from Go client exe windows 64bits?

### ISSUE THREAD

**Issue by jmptrader** [go-ole/go-ole#118]
Hello,

I have an VMBox with  windows & golang 32 bits  and an legacy activex.
In this run ok, invoke, get/put properties.-

But an VMBox with  windows 7 64bits , golang 64 bits  and an legacy activex.
Not run ok.  If I rebuild in system 32bits end-to-end then run ok on windows 64bits.  

What is the problem?

Thanks,
JM

**Comment by mattn** [comment]
could you please show me your code?

**Comment by jacobsantos** [comment]
The problem appears to be that 32-bit service can not run in process with a 64-bit application. You would have to set the code up to run the ActiveX, if not already, to run outside of the go application. If you desire to run the ActiveX in-process or can only run the ActiveX in process, then the architecture has to match.

**Comment by jmptrader** [comment]
ok, thanks very much.

The legacy ActiveX is an 32bits DLL (from third party). The best path is build all in 32bits architecture and run in 64bit environment.
