### ISSUE TITLE
Q: How to call D3D9 COM Functions from pure Go?

### ISSUE THREAD

**Issue by gonutz** [go-ole/go-ole#140]
This is not actually an issue, I am just trying to get in contact with the authors of this package because I need your help.

I am the author of the [d3d9 package](https://github.com/gonutz/d3d9) which is a CGo wrapper for using Direct3D9 from Go. The package loads the d3d9.dll dynamically and uses the MinGW C header files to call the COM methods of the D3D9 objects via a thin CGo wrapper.

I was hoping to get rid of the CGo wrapper and call COM methods directly from Go. This way there would be no need for a C Compiler when using the package on Windows (installing MinGW is always a pain).

Could you give me an example of how I can load the d3d9.dll, call `Direct3DCreate9` which gives me a COM object back, and then the important part: **call methods on that COM object** from Go?

Thank you very much in advance!

**Comment by mattn** [comment]
d3d9 doesn't have generally COM vtbl. for example, it doesn't have IDispatch interface. But you can do it with writing all interface in go.

```go
package main

import (
	"fmt"
	"log"
	"syscall"
	"unsafe"
)

const (
	D3D9_SDK_VERSION = 32
)

var (
	libd3d9             = syscall.NewLazyDLL("d3d9.dll")
	procDirect3DCreate9 = libd3d9.NewProc("Direct3DCreate9")
)

type IDirect3D struct {
	lpVtbl *IDirect3DVtbl
}

type IDirect3DVtbl struct {
	QueryInterface uintptr
	AddRef         uintptr
	Release        uintptr

	RegisterSoftwareDevice      uintptr
	GetAdapterCount             uintptr
	GetAdapterIdentifier        uintptr
	GetAdapterModeCount         uintptr
	EnumAdapterModes            uintptr
	GetAdapterDisplayMode       uintptr
	CheckDeviceType             uintptr
	CheckDeviceFormat           uintptr
	CheckDeviceMultiSampleType  uintptr
	CheckDepthStencilMatch      uintptr
	CheckDeviceFormatConversion uintptr
	GetDeviceCaps               uintptr
	GetAdapterMonitor           uintptr
	CreateDevice                uintptr
}

func (v *IDirect3D) AddRef() int32 {
	ret, _, _ := syscall.Syscall(
		v.lpVtbl.AddRef,
		1,
		uintptr(unsafe.Pointer(v)),
		0,
		0)
	return int32(ret)
}

func (v *IDirect3D) Release() int32 {
	ret, _, _ := syscall.Syscall(
		v.lpVtbl.Release,
		1,
		uintptr(unsafe.Pointer(v)),
		0,
		0)
	return int32(ret)
}

func (v *IDirect3D) GetAdapterCount() uint32 {
	ret, _, _ := syscall.Syscall(
		v.lpVtbl.GetAdapterCount,
		1,
		uintptr(unsafe.Pointer(v)),
		0,
		0)
	return uint32(ret)
}

func main() {
	v, r, err := procDirect3DCreate9.Call(uintptr(D3D9_SDK_VERSION))
	if r != 0 && err != nil {
		log.Fatal(err)
	}
	d3d := *((**IDirect3D)(unsafe.Pointer(&v)))

	d3d.AddRef()
	defer d3d.Release()

	fmt.Println(d3d.GetAdapterCount())
}
```

**Comment by gonutz** [comment]
Great! Thank you so very much for the running example! I have been trying this for some time now and could not get it to work. You really helped me out a lot here. Now I will be able to get rid the C Compiler which will make installing the lib much easier.

Thank you again, I really appreciate this! :-)

**Comment by gonutz** [comment]
Hey, thanks again, I was able to implement a pure Go wrapper for Direct3D and DirectSound, thanks to your suggestion. I appreciate your support very much. Thank you!

**Comment by mattn** [comment]
Coooool! 👍
