### ISSUE TITLE
Old format or invalid type library

### ISSUE THREAD

**Issue by victron** [go-ole/go-ole#145]
Hello,
Could you answer on my query?
I got an error 
```
C:\Users\vtsymbal\Documents\_ALU_priv\GO\src\github.com\go-ole\go-ole\example\excel (master)
λ go run excel.go
panic: Old format or invalid type library.
goroutine 1 [running]:
github.com/go-ole/go-ole/oleutil.MustCallMethod(0x22db18, 0x4d50bd, 0x3, 0xc04202ff18, 0x1, 0x1, 0xc04203cfa0)
        C:/Users/vtsymbal/Documents/_ALU_priv/GO/src/github.com/go-ole/go-ole/oleutil/oleutil.go:58 +0xe7
main.main()
        C:/Users/vtsymbal/Documents/_ALU_priv/GO/src/github.com/go-ole/go-ole/example/excel/excel.go:18 +0x1de
exit status 2
```

If I change regional settings in windows - everything fine. But anyway could you advice does it possible to implement workaround described here [System.Globalization.CultureInfo](https://support.microsoft.com/en-us/help/320369/bug-old-format-or-invalid-type-library-error-when-automating-excel). Could you show example, how it should be according your API.
Sorry, for disturbing.

**Comment by mattn** [comment]
System.Globalization.CaltureInfo is not COM object. Try to make your locale-ID directory in "Microsoft Office\Office11".

**Comment by victron** [comment]
Thank you for suggestion.
