### ISSUE TITLE
How to get a correct error code from a ole.OleError struct

### ISSUE THREAD

**Issue by dionyself** [go-ole/go-ole#148]
I'm running go-ole code on Windows 7 and it seems that **error_codes are not matching with its description**.
code:
`
err := ole.CoInitializeEx(0, ole.COINIT_MULTITHREADED)
errDetails := err.(*ole.OleError)
fmt.Printf("%s", errDetails.Code())
`
but i get always the same 0x80020009 (wrong) error code,  i was expecting  the correct code `0x800706ba` for the error `The RPC server is
unavailable.`

you can verify this by running 
`wbemtest` on windows
then click `connect`  and use  `\\hostname\root\cimv2` as namespace

Extra:
   ole.OleError.String() seems to be broken too (error_code is missing).

**Comment by mattn** [comment]
Please show me your code which can reproduce.

**Comment by dionyself** [comment]
Thanks @mattn  you can reproduce the error with this code:

```package main
import "github.com/StackExchange/wmi"
import "github.com/go-ole/go-ole"
import "log"
import "reflect"


type Bios struct {
	Name              *string
	SerialNumber      *string
	SMBIOSBIOSVersion *string
	Version           *string
}

func (this Bios) Query(host, user, pass string) (interface{}, reflect.Type, error) {
	refList := []Bios{this}
	q := wmi.CreateQuery(&refList, "")
	err := wmi.Query(q, &refList, host, `root\CIMV2`, user, pass)
	if err != nil {
		errDetails := err.(*ole.OleError)
		errCode := errDetails.Code()
		log.Printf("Error %#x: %s (error %d), on Entity: %s", errCode, err, errCode, reflect.TypeOf(this))
		return nil, nil, err
	}
	return refList, reflect.TypeOf(&this), nil
}

func main() {
  connector := Bios{}
  connector.Query("10.0.2.123", "user", "pass")
}
```
you can compile it on linux:`CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -a -installsuffix cgo -ldflags "-X main.VersionString=$MAIN_ENVARS" -o demo.exe .`

**Comment by mattn** [comment]
Well, you should get the error with ole.CoInitializeEx. Right? Then, I guess you can reproduce with out wmi.

**Comment by mattn** [comment]
Now I figure out this. And I added WCode and SCODE for EXCEPINFO. Now you can get it.

```go
		errDetails := err.(*ole.OleError)
		errCode := errDetails.Code()
		log.Printf("Error %#x: %s (error %d), on Entity: %s", errCode, err, errCode, reflect.TypeOf(this))
		subErr := errDetails.SubError().(ole.EXCEPINFO)
		fmt.Println("%x", subErr.SCODE())
```

**Comment by dionyself** [comment]
Working fine, thanks
