### ISSUE TITLE
MustPutProperty function assignment IDispatch type error

### ISSUE THREAD

**Issue by libs3** [go-ole/go-ole#154]
ole.CoInitialize(0)
defer ole.CoUninitialize()

unknown, err := oleutil.CreateObject("SAPI.SPVoice")
if err != nil {
		log.Fatal(err)
}
spv := unknown.MustQueryInterface(ole.IID_IDispatch)
defer spv.Release()

unknown, err = oleutil.CreateObject("SAPI.SpFileStream")
if err != nil {
		log.Fatal(err)
}
spf := unknown.MustQueryInterface(ole.IID_IDispatch)
defer spf.Release()

oleutil.MustPutProperty(spv, "AudioOutputStream", spf)//!!!!

--------------------------------------------------------------------
panic: 找不到成员。//member not found
  
  goroutine 1 [running]:
  github.com/go-ole/go-ole/oleutil.MustPutProperty(0x323f2ae8, 0x4bc6da, 0x11, 0x11f01fa0, 0x1, 0x1, 0x0)
    E:/code/go/src/github.com/go-ole/go-ole/oleutil/oleutil.go:86 +0xa7
  main.main()
    E:/code/go/src/tima.com/ceshi/main/testole2.go:39 +0x1e5
  exit status 2
------------------------------------------------------------------------------
Who can tell me how to solve it? 
Thank you very much

**Comment by mattn** [comment]
How works if use MustGetProperty?

**Comment by libs3** [comment]
The AudioOutputStream property of SPVoice needs to pass the SpFileStream object.
The IDispatch object obtained by MustGetProperty can not be used either.

**Comment by mattn** [comment]
please try to call `oleutil.MustPutProperty(spv, "AudioOutputStream")`

**Comment by libs3** [comment]
oleutil.MustPutProperty(spv, "AudioOutputStream")
---------------------------------------------------------------------------------
panic: 参数错误。//Parameter error
  
  goroutine 1 [running]:
  github.com/go-ole/go-ole/oleutil.MustPutProperty(0x1da2ad8, 0x4bc69a, 0x11, 0x0, 0x0, 0x0, 0x12076000)
    E:/code/go/src/github.com/go-ole/go-ole/oleutil/oleutil.go:86 +0xa7
  main.main()
    E:/code/go/src/tima.com/ceshi/main/testole2.go:38 +0x1bf
  exit status 2

**Comment by mattn** [comment]
added oleutil.PutPropertyRef. Now you can use it.

```go
package main

import (
	"log"

	"github.com/go-ole/go-ole"
	"github.com/go-ole/go-ole/oleutil"
)

func main() {
	ole.CoInitialize(0)
	defer ole.CoUninitialize()

	unknown, err := oleutil.CreateObject("SAPI.SPVoice")
	if err != nil {
		log.Fatal(err)
	}
	spv := unknown.MustQueryInterface(ole.IID_IDispatch)
	defer spv.Release()

	unknown, err = oleutil.CreateObject("SAPI.SpFileStream")
	if err != nil {
		log.Fatal(err)
	}
	spf := unknown.MustQueryInterface(ole.IID_IDispatch)
	defer spf.Release()

	oleutil.MustCallMethod(spf, "open", "test.wav", 3)

	oleutil.MustPutPropertyRef(spv, "AudioOutputStream", spf) //!!!!
}
```
