### ISSUE TITLE
Outlook send message

### ISSUE THREAD

**Issue by dmp73** [go-ole/go-ole#160]
Could you please help with example of sending message in Outlook ?
I have no experience to adapt existing example of listing contacts.

**Comment by cmarkh** [comment]
I was able to send messages using the following: 

`func send() error {
	ole.CoInitialize(0)
	unknown, err := oleutil.CreateObject("Outlook.Application")
	if err != nil {
		log.Print(err)
		return err
	}
	outlook, err := unknown.QueryInterface(ole.IID_IDispatch)
	if err != nil {
		log.Print(err)
		return err
	}
	newmail := oleutil.MustCallMethod(outlook, "CreateItem", "0").ToIDispatch()
	oleutil.MustPutProperty(newmail, "Subject", "test")
	oleutil.MustPutProperty(newmail, "To", "example@example.com")
	oleutil.MustPutProperty(newmail, "HTMLBody", "Testing")
	oleutil.MustCallMethod(newmail, "Send").ToIDispatch()

	return nil
}`

**Comment by dmp73** [comment]
Thanks.
Already solve this:

func main() {
	ole.CoInitialize(0)
	unknown, _ := oleutil.CreateObject("Outlook.Application")
	outlook, _ := unknown.QueryInterface(ole.IID_IDispatch)
	msg := oleutil.MustCallMethod(outlook, "CreateItem", 0).ToIDispatch()
        recip := oleutil.MustGetProperty(msg, "Recipients").ToIDispatch()
        oleutil.MustCallMethod(recip, "Add", "test@test.com").ToIDispatch()
        oleutil.PutProperty(msg, "Subject", "Test")
        oleutil.PutProperty(msg, "Body", "qwerty")
        oleutil.MustCallMethod(msg, "Send").ToIDispatch()
}

**Comment by clementlefevre** [comment]
First, thanks for this very cool package. 
Just for whoever might be interested, hereby the same example with adding an attachement :


```go
func send() error {
	ole.CoInitialize(0)
	unknown, err := oleutil.CreateObject("Outlook.Application")
	if err != nil {
		log.Print(err)
		return err
	}
	outlook, err := unknown.QueryInterface(ole.IID_IDispatch)
	if err != nil {
		log.Print(err)
		return err
	}
	newmail := oleutil.MustCallMethod(outlook, "CreateItem", "0").ToIDispatch()
	oleutil.MustPutProperty(newmail, "Subject", "test")
	oleutil.MustPutProperty(newmail, "To", "example@example.com")
	oleutil.MustPutProperty(newmail, "HTMLBody", "Testing")
	newAtt := oleutil.MustGetProperty(newmail, "Attachments").ToIDispatch()
	oleutil.MustCallMethod(newAtt, "Add", "d:/Users/workspace/golang_playground/email_send/test.txt")
	oleutil.MustCallMethod(newmail, "Send").ToIDispatch()

	return nil
}
```
