### ISSUE TITLE
i have a ocx created by vb

### ISSUE THREAD

**Issue by dengxuesong** [go-ole/go-ole#167]
i have a ocx created by vb, after i call createobject it return error -2146827949, how this happend, please help me.

**Comment by dengxuesong** [comment]
the cocreateinstance return error code -2146827949  why this happen?

**Comment by mattn** [comment]
The error code is FACILITY_CONTROL.

**Comment by mattn** [comment]
Can you call it from VBS?

**Comment by dengxuesong** [comment]
vbs is ok.
 when i use vs2010 to load  the ocx，it return similar error code.
the code is like this
	CLSID wedsclsid;
	  IDispatch *myobj;
	  HRESULT hr;
	  CoInitializeEx(NULL,COINIT_APARTMENTTHREADED);
	  hr = CLSIDFromProgID(L"WEDS4_CommSV3.W4commsv3",&wedsclsid);
	  hr = CoCreateInstance(wedsclsid,NULL,CLSCTX_SERVER,IID_IDispatch,(void **)&myobj);
	  CoUninitialize();
but  i found one tool to load the ocx ,it can show the interface of the ocx.

whether i need another way to load the ocx ? 
can you give a suggestion?

**Comment by mattn** [comment]
Could you please show me your Go code?

**Comment by dengxuesong** [comment]
pid := "WEDS4_CommSV3.W4commsv3"
	//pid = "FANCY3DOCX.Fancy3DOCXCtrl.1"
	ole.CoInitializeEx()
	err := ole.CoInitialize(0)
	if err!=nil{
		fmt.Println(err.Error())
		return
	}
	clsid,err := ole.CLSIDFromProgID(pid)
	if err!=nil{
		fmt.Println(err.Error())
		return
	}
	fmt.Println(clsid.String())
	unknown, err := ole.CreateInstance(clsid,nil)
	fmt.Println(unknown)
	if err!=nil{
		fmt.Println("create object failed")
		fmt.Println(err)
		return
	}
	ins, err := unknown.QueryInterface(ole.IID_IDispatch)
	if err!=nil{
		fmt.Println(err.Error())
		return
	}
	fmt.Println(ins)
	ole.CoUninitialize()

**Comment by dengxuesong** [comment]
"FANCY3DOCX.Fancy3DOCXCtrl.1"  is ok , it created by vc.
"WEDS4_CommSV3.W4commsv3" is wrong, it created by vb.
vb vc  some different?

**Comment by dengxuesong** [comment]
//ole.CoInitializeEx()

**Comment by dengxuesong** [comment]
http://www.51jfss.com/static/w4commsv3.ocx.tar.bz2
i put it to server,can you help me to found the problem .

**Comment by mattn** [comment]
If the error is occured on vs2010 too, this is not an issue of go-ole. Right?

**Comment by dengxuesong** [comment]
maybe?  i'm confused.
does go-ole support vb activex ocx?

**Comment by mattn** [comment]
Does your OCX built in VB export the methods or properties? Also inherit System.Runtime.InteropServices?

**Comment by mattn** [comment]
Question again. Did you try this VBS?:

```
Set o = CreateObject("WEDS4_CommSV3.W4commsv3")
```

**Comment by dengxuesong** [comment]
i am sorry for waste your time，it's my fault.  the ocx need the vb6‘s environment.
go-ole is excellent. for handle ocx..

**Comment by mattn** [comment]
Good to hear. So closing.
