### ISSUE TITLE
Failed to build test?

### ISSUE THREAD

**Issue by colincoates** [go-ole/go-ole#171]
Hi, I have just followed the "Install" instructions:

>go get github.com/go-ole/go-ole
>cd /path/to/go-ole/
>go test`

I see an error message on running "go test":
>.\com_test.go:197: Fatalf call has arguments but no formatting directives
>FAIL    github.com/go-ole/go-ole [build failed]`

I am using:
>go version go1.10.3 windows/amd64

Am I doing something wrong, or is this a real issue, please?

**Comment by mattn** [comment]
It was already fixed. https://github.com/go-ole/go-ole/commit/53bb65ff9d17568304350a86472d7107d1853275
