### ISSUE TITLE
safeArrayGet*Bounds return type

### ISSUE THREAD

**Issue by adnsv** [go-ole/go-ole#172]
There is an issue with safeArrayGetLBound and safeArrayGetUBound.

API in these functions is called with the third parameter referencing `int64`, however, the original API specs indicate that this should be a reference to a `long` value, which is a 32-bit signed for both Win32 and Win64.

This causes problems for an empty array, then the upper bound is -1 because long(-1) is not the same as int64(-1). The casting then incorrectly returns 4294967295 instead of -1 thus failing subsequent TotalElements() calculation result returning 4294967296 instead of 0.

When using SafeArrayConversion.ToStringArray(), for example, this results "out of memory" panic.

**Comment by troian** [comment]
@adnsv I made PR with your description if you don't mind

**Comment by troian** [comment]
@mattn any chance merged fix can be tagged? Just would be easier to track dependencies.

**Comment by mattn** [comment]
Tagged v1.2.2

**Comment by troian** [comment]
Thanks
