### ISSUE TITLE
How is ole.VARIANT used in syscalls? (amd64)

### ISSUE THREAD

**Issue by frieder-audriga** [go-ole/go-ole#179]
Hi, as stated above I was wondering how to use VARIANT in 64 bit syscalls.
My case is with VARIANT with ole.VT_BSTR as VT.

In the following I will write Value as ValuePart1 and ValuePart2, since it is 8 byte long and uintptr are only 4 byte long in 386. I will also abbreviate wReseved1 to wR1 for a better Overview.
With your [VARIANT](https://github.com/go-ole/go-ole/blob/master/variant_386.go) file and https://docs.microsoft.com/en-us/windows/desktop/api/oaidl/ns-oaidl-tagvariant I understand, that the variant structure looks as follows:

![VARIANT_386](https://i.imgur.com/qO6Zbim.png "VARIANT_386")

I have seen your VARIANT used in a 32 bit syscall as follows:

![VARIANT_386 Syscall](https://imgur.com/aAxcVWd.png "VARIANT_386 Syscall")

(Source: [This Microsoft Automation API function](https://docs.microsoft.com/en-us/windows/desktop/api/uiautomationclient/nf-uiautomationclient-iuiautomation-createpropertycondition) was rewritten in go using your library: [Rewritten function](https://github.com/hnakamur/w32uiautomation/blob/963c5586ab7f8b60017d232e90439706bccb33e5/iuiautomation_386.go#L11), uses [helper-function](https://github.com/hnakamur/w32uiautomation/blob/963c5586ab7f8b60017d232e90439706bccb33e5/variant_386.go#L14))
I have tested it and it works.
Now I assume, that the wReserved values can just be assumed to be zero, but what is strange is that VT and wR1 have been swapped and that the order of the Value parts have been swapped.
But this seems to be the correct order since like this the syscall works as expected.

Now I want to call this function in 64 bit.

According to your [VARIANT.go](https://github.com/go-ole/go-ole/blob/master/variant_amd64.go) the structure looks like this under amd64

![VARIANT_amd64](https://imgur.com/QIji7gr.png "VARIANT_amd64")
Now I will assume that the Value you ignored with _ can be just set to 0 when doing a syscall.
I have tried many different orders in which to put the parts of the VARIANT in the syscall arguments, but with most I only received an  0xc0000005 (Access Violation) Exception.
Only after I have put VT to start at byte 4 I received different kinds of errors.
When bytes 8 to 15 were empty (and the Value was in the part from 16 to 23) I received an invalid pointer error,
When I put Value in bytes 8 to 15 in correct order I received an "The parameter is incorrect." error message  
![VARIANT_amd64 Syscall](https://imgur.com/TNDqxgH.png "VARIANT_amd64 Syscall")
but trying to swap the order like it was done in the 386 syscall results again in an access violation error.

So I would assume the order as visualized above is still wrong but the most correct I can think of.

What am I missing here? How can I use a VARIANT in a 64 bit Syscall?

Note: I have also tried just giving a pointer to the VARIANT struct in the syscall but unfortunalley this did not work either.
Other Note: [This](https://docs.google.com/spreadsheets/d/15vTGadly4asb9rAg9ydXHdRNNolaxHDbtbyQoMJfR_s/edit?usp=sharing) is the spreadsheet I have used to document how I understand VARIANT works.

**Comment by frieder-audriga** [comment]
Thank you for your answer.
I have tried your solution but unfortunately it does not fix the problem. I receive the exact same error message as before ("The parameter is incorrect.")

I was hoping that you could maybe explain why VT and both Value halves have to be placed in a 32 bit syscall like I described above and how to place them in a 64 bit syscall

**Comment by wutka** [comment]
Now that I have had more sleep, I realize that the byte array is equivalent to passing a pointer to the ole.VARIANT, which works, as it turns out, at least for 64-bit. I tried changing the 32-bit version to pass a pointer to the VARIANT but it seems to still need the weird arrangement that frieder-audriga posted about.

**Comment by frieder-audriga** [comment]
Wow, thank you, this really did the trick.
I can confirm, that passing a pointer to the VARIANT (Either as a byte array or directly as`uintptr(unsafe.Pointer(&variant))`) does work.
I must have made a mistake earlier that lead me to believe/write 
> I have also tried just giving a pointer to the VARIANT struct in the syscall but unfortunalley this did not work either.

Sorry about that.

While I am still confused as to why the strange arrangement is necessary in the 32 bit version but not in the 64 bit version, this does answer the question, that a VARIANT can be used in a syscall under amd64 by passing a pointer to it. Thank you
