### ISSUE TITLE
Checksum verification error: version tag v1.2.2 was changed?

### ISSUE THREAD

**Issue by dragetd** [go-ole/go-ole#185]
We are using go modules and noticed that the tag v1.2.2 had its checksum suddenly changed when running go build:

```
go: verifying github.com/go-ole/go-ole@v1.2.2/go.mod: checksum mismatch
	downloaded: h1:pnvuG7BrDMZ8ifMurTQmxwhQM/odqm9sSqNe5BUI7v4=
	go.sum:     h1:7FAglXiTm7HKlQRDeOQ6ZNUHidzCWXuZWq/1dTyBNF8=
```

Has the tag been force-pushed with new changes or what happened here? If so, what are the exact changes?

**Comment by flibustenet** [comment]
@mattn is currently adding `go.mod` file #184 
I believe it's because of that ? Maybe after that it need to be tagged v1.2.3 or v1.3.0

**Comment by dragetd** [comment]
I am aware that there are are caching module proxies that allow to keep up internal development process while the upstream issue is resolved.

But this one should have really been a different version. Once a tag is set on go projects, one should really keep it as it is.

**Comment by mattn** [comment]
I'll remove&create go.mod again.

**Comment by mattn** [comment]
Now I re-generated go.mod (removed go.sum). And tagged 1.2.4.

**Comment by flibustenet** [comment]
`go.sum` should be versioned also

**Comment by mattn** [comment]
I did `go mod init && go mod tify`. But `go.sum` is not generated.

**Comment by mattn** [comment]
Probably, go-ole does not have any dependencies.

**Comment by flibustenet** [comment]
You're right, fine that go-ole do not have dependencies :+1:

**Comment by mattn** [comment]
So closing. If you still have problem, please reopen this. Thanks.
