### ISSUE TITLE
some function not implementation?

### ISSUE THREAD

**Issue by 756445638** [go-ole/go-ole#186]
// safeArrayGetIID is the InterfaceID of the elements in the SafeArray.
//
// AKA: SafeArrayGetIID in Windows API.
func safeArrayGetIID(safearray *SafeArray) (*GUID, error) {
	return nil, NewError(E_NOTIMPL)
}

this function has no implementation, but I just need , can you fix it??

**Comment by 756445638** [comment]
can you fix this please!!

**Comment by mattn** [comment]
It is already implemented in safearray_windows.go
