### ISSUE TITLE
Using WMI ExecNotificationQuery 

### ISSUE THREAD

**Issue by dlopes7** [go-ole/go-ole#195]
Hello folks,

I am migrating an application from C++, that needs to listen for ExecNotificationQuery events.
In C++ I do so by calling that method, and then calling `Next` on the `CComPtr<IEnumWbemClassObject>`, like so:

```c++
ExecNotificationQuery(_bstr_t(L"WQL"), "SELECT * FROM __InstanceOperationEvent WITHIN 10 WHERE ( TargetInstance ISA 'Win32_Process')"",
                                                  WBEM_FLAG_FORWARD_ONLY | WBEM_FLAG_RETURN_IMMEDIATELY, nullptr,
                                                  &m_enumerator)
HRESULT hr = m_enumerator->Next(WAIT_TIMEOUT_MS, 1L, &obj, &retcnt);
```

Is it possible to do something similar with go-ole? I am having a hard time understanding how to invoke that `Next` method.

**Comment by dlopes7** [comment]
I think I figured it out, I was getting too caught up on C++

`event, err := queryRaw.ToIDispatch().CallMethod("NextEvent")`

Is the method I am looking for, and it is documented here https://docs.microsoft.com/en-us/windows/win32/wmisdk/swbemeventsource-nextevent

**Comment by yalegko** [comment]
We've already had a go implementation of WMI Notifications queries :) 

Take a look at https://pkg.go.dev/github.com/bi-zone/wmi?tab=doc#NotificationQuery
