### ISSUE TITLE
How to make a struct ComVisible with Go-Ole?

### ISSUE THREAD

**Issue by yusufbuyruk** [go-ole/go-ole#200]
I need to implement following C# code in Go language,

`using System.Runtime.InteropServices;

namespace ComVisible
{
    [ComVisible(true)]
    [ClassInterface(ClassInterfaceType.AutoDispatch)]
    public class ComVisibleClass
    {
        public void SomeFunctions()
        {
            ....
        }
    }
}`

I cannot make a golang struct ComVisible(true) and AutoDistatch functionality?

Any idea?

**Comment by yusufbuyruk** [comment]
I have two questions,

1 - Is this possible to produce a COM object with go-ole? If yes, could you please share the link please?

2- I do not know much about WinRT, but I thought it is a similar technology with Component Object Model. Is it possible to produce WinRT object?

Thanks

**Comment by mattn** [comment]
1. It's possible to do with https://github.com/go-ole/com
2. No. go-ole provide only COM it self.

ComVisible is attribute to enable the interfaces to be used as COM on .NET .

**Comment by yusufbuyruk** [comment]
Thanks for your help @mattn 
much appreciated
