### ISSUE TITLE
Question: GetActiveObject Applicable Situation

### ISSUE THREAD

**Issue by kevinxxq** [go-ole/go-ole#236]
Hi There,
I tried to get active instance of my COM as below:
```
	ole.CoInitialize(0)
	myCOM:="mycom"
	unknownCreate, _ := oleutil.CreateObject(myCOM)
	fmt.Println("unknownCreate:", unknownCreate)

	unknownGet, errGet := oleutil.GetActiveObject(myCOM)

	fmt.Println("unknownGet:", unknownGet)
	fmt.Println("errGet:", errGet == nil)

	if errGet != nil {
		fmt.Println("errGet:", errGet.Error())
	}

	ole.CoUninitialize()
```

the output:
```
unknownCreate: &{0x7ff9fbbc4b38}
unknownGet: <nil>
errGet: false
errGet: 操作无法使用   <-check the error in english as below:

github.com/go-ole/go-ole.OleError {hr: 2147746275, description: "", subError: error nil}
hr:
2147746275 = 0x800401e3

check the error code:
2147746275,  "Operation unavailable\r\n"
```

in case run with excel, the output is:
```
unknownCreate: &{0x7ff9fbbc4b38}
unknownGet: &{0x7ff9fbbc4b38}
errGet: true
```
Does this mean there is a problem of my COM(not support GetActiveObject)?
Is there any alternative way to achieve it?

I searched this issue and may find some related contents, the problem is from the COM itself(even with Excel):
[](https://support.microsoft.com/en-us/topic/getobject-or-getactiveobject-cannot-find-a-running-office-application-6cdf21a3-ac90-512b-6bff-badc5f4cc215)

> Although the Office application is running, it might not be registered in the Running Object Table (ROT). A running instance of an Office application must be registered in the ROT before it can be attached to using GetObject (Visual Basic) or GetActiveObject (Visual C++).

> 

Any idea or workarround is appriciated.
Thank you.

**Comment by jacobsantos** [comment]
Sorry for the delay. The library access the underlying system libraries for COM access. If it is not working, then it is likely that third-party means would need to be used.

It is likely that you may need to perform some setup steps or poll the system through another library or API, to see whether the application is ready to be polled. This does not seem to be something that we can help with (albeit after this long, it is unlikely to be a concern).
