### ISSUE TITLE
Write integration tests to fully test library

### ISSUE THREAD

**Issue by jacobsantos** [go-ole/go-ole#24]
I think it is time to break out the C++ or C# Visual Studio coding (probably go with C#) to develop a integration test suite. The current issues could be resolved with more test cases that test a number of the issues being brought up.

The proposal is to develop a COM server that implements a number of basic and advanced functions that will utilize each of the functions within the Go library. As well as address some of the issues that were brought up to ensure that similar issues are not introduced in the future.

Other tests should involve common COM server that all Windows machines should have installed to further allow testing against whatever can be called to further insure stability.

This may also involve finishing the library just for completion sake and to ensure that the library is production ready. Given that more people appear to be using the library.

**Comment by jacobsantos** [comment]
Visual Studio Community 2013 allows for creating C# COM servers. I'm going to start on this, this week. I'm probably going to move it to its own repository. I'll put a link here later.

**Comment by jacobsantos** [comment]
Okay, I finally have all of the resources I need to start this project. It will help with the documentation. Not sure how long it will take, but I'll be working within my fork.

**Comment by mattn** [comment]
Looking Good! :clap:

**Comment by jacobsantos** [comment]
I'm currently investigating using AppVeyor for the continuous integration build and testing while developing. I'm not sure if you'd want to merge that over, since whether or not it costs money is a question I still have. They say that open source projects can use the service for free, but I'm not sure about the terms.

You may also look at Travis-CI for building on Linux and testing a few bugs that might come up while building on Linux. I'm hoping that a good Mac OS X online build service starts up, and I don't know if Travis-CI allows go builds on their Mac OS X systems. Looking at the documentation doesn't suggest that to be the case.

Providing a vagrant file will allow for better testing of cross builds on Linux for Windows. It will compile the COM server, register it, compile the go test COM client application on Linux and run it on Windows.

The only other thing to provide would be a gulp or grunt that automatically runs all of the tests.

I'm also thinking that the COM Server should be provided as an shared library (dll) for both Windows IA32 and AMD64. This way, to test, you would only have to download the dll, register it, and then run the tests for the library. A gulp or grunt file could automate this process for the developer.

**Comment by mattn** [comment]
Currently, go doesn't provide way to create DLLs.

**Comment by jacobsantos** [comment]
Yes. The DLL will be the C# .NET project that is the COM server.

**Comment by jacobsantos** [comment]
I did another project test to see how easy it would be to create a COM server in C#. I have to say that it is incredibly simple and quick. I am going to work on it tonight and see about having it completed over the weekend.

I'm going to create the test cases and move the examples to the test COM server on this repository first and then work on the other repositories.

**Comment by jacobsantos** [comment]
Travis-CI has been added. Builds are running on my fork.

@mattn I don't have access to setup builds on Travis-CI for ole-go group. I wonder if you do. Really, the only thing that matters is that the build is working. Travis-CI wants to run the unit tests, which fail on Linux.

I'm going towards the **ignore all tests on linux** solution. Really, I just want to check that the build succeeds on Linux and correct for any errors. I'm going to attempt AppVeyor next, but I'm still working on the C# COM server for testing.

I figure it would be better to just get the CI checking the builds first and then work on actually running the tests. However, Travis-CI is not checking the builds for Windows, so the build might be failing. Last time I checked AppVeyor, it was difficult to get anything going. I'm going to check again briefly to see if I can get something up.

**Comment by jacobsantos** [comment]
Okay, I added AppVeyor configuration. I'm running a build off of my fork now. It is slow, so might want to switch to a custom Azure instance (if free) instead.

Or I guess simply testing locally would work too. No fun really. I wish you could test pull-requests on AppVeyor like you can on Travis-CI. That is a really neat feature that doesn't solve anything for the library.

**Comment by jacobsantos** [comment]
Only thing missing now is proper COM Test Server application. I should hopefully have that done over the weekend. Have to figure out how to add it to the AppVeyor build process.

**Comment by jacobsantos** [comment]
I'm unsure if this should include tests for every function. Part of me thinks it should because it will not catch mistakes in the syscall otherwise. I do think that the tests that will be easy to do should be done.

At the moment, I'm still putting together the type tests. What this does is allow for setting and retrieving a type and calling a method through either dispatch of virtual table.

I'm not entirely sure how to go about testing all of the COM interfaces. At the moment, I'm focusing on just `IUnknown` and `IDispatch`. Once I figure out `IConnectionPoint` and `IConnectionPointContainer`, then I will do those. My goal is to test all of the interfaces, but this might just be part of the separate COM packages instead of the `go-ole` package.

The next part is figuring out to do Dates and Decimal values in order to test those. I'm not sure how often those are used. I'm guessing they it is rare, since most would just return float and strings instead of Date and Decimal objects. My goal is to attempt to support as much as possible and hopefully, whatever I don't support, someone else will write tests for.

I think SafeArray is pretty easy, I believe all I have to do is return an array and the TLB will specify SafeArray and .NET runtime will do the conversions. It is slow because I have to figure out how to do other tests and move the examples and the rest of the tests over to the new test COM server.

**Comment by mattn** [comment]
> The next part is figuring out to do Dates and Decimal values in order to test those. I'm not sure how often those are used. I'm guessing they it is rare,

I think so.

I stil wonder what i should provide interfaces to use extra packages.

**Comment by jacobsantos** [comment]
> I stil wonder what i should provide interfaces to use extra packages.

I would say that it should be provided to prevent forcing others to provide it themselves. I was thinking about a second repository matching go-ole-interfaces with the extra interfaces not currently in the go-ole repository.

I'm still planning on creating the com generation tool. I switched gears over to testing, since it should be easier to do and it would provide more tests for `go-ole` and the `com` packages. The COM package needs to be tested before the com generation tool can be coded, since it needs to work. The other packages also need to be tested.

It is slow right now, because Destiny and Witcher 3, but the test COM server is pretty small and easy, so shouldn't take that much longer. Need to do arrays and I'm researching and looking at what other functions need tests. At the rate, it might be another week, but after that, the `go-ole` will have better test coverage at least. 

My goal is to make that more complete, but that might be a little more difficult or time consuming given the integration testing. I'm hoping that someone else will carry the torch after I start it, but probably just create tests as bug tickets arrive.

So, creating the interfaces or adding the interfaces after the COM generation tool is finished, should be pretty quick. The goal is that if you have a dual or virtual table interface or object, that it will create the functions and attempt to fill out as much as possible of the functions as possible. If it is simply IDispatch, then it should be able to fill out the complete interface and object type info. It is how I plan on completing the interfaces for the separate interface packages. The COM generation tool will also work with `go-ole`, so the goal is that adding or updating COM interfaces will be automated.

**Comment by mattn** [comment]
> I'm still planning on creating the com generation tool.

do you mean a tool to generate COM wrapper for go?

**Comment by jacobsantos** [comment]
Yes. It generates code for COM interfaces using `go-ole` or `com` packages in either virtual table or idispatch based on the type lib info and COM interfaces.

**Comment by mattn** [comment]
BTW, in 7 or 8 years ago, i made java-com bridge in my job. And wrote generator similar to it. :)

**Comment by jacobsantos** [comment]
Cool! Code generators are the future I think. It is nice that golang has it practically built in to the workflow and that it also has easier access to the AST.

**Comment by jacobsantos** [comment]
I took a break from development for the moment. I need to make sure I'm addressing the new libraries correctly and doing some research for the upcoming COM generation tool in a side project. Also, Witcher 3 and work projects. Should be back in a few weeks or no more than 2 months. Should be fun. Not going to be another 2 or 3 year break, I don't believe. Will take another break when AC: Syndicate comes out. Witcher 3 is taking a lot of time, probably have 100+ hours already. Not even close to finishing.

**Comment by jacobsantos** [comment]
@mattn Update and bump.

The DLL is building and appears to be working with the appveyor build process in my fork. I will probably only have enough time today to confirm that everything is working. I'm going to see about using the rest of the this week to actually write tests and extend the COM Test Server to cover SafeArrays, ENUMs and Dates and other types.

@mattn Can you sign up for Appveyor and see if you can add the test-com-server repo and this repo? I can't add them and it will help with pull requests on both repositories if Appveyor is added as well. Not sure what the deal is or why I can't add it. I was able to add go-ole to Travis CI, but that basically only checks that nothing is broken on Linux.

**Comment by mattn** [comment]
https://ci.appveyor.com/project/mattn/test-com-server/build/job/jxvg50w0lpog2t25

**Comment by jacobsantos** [comment]
@mattn I'm unsure how to customize appveyor.yml for different forks. You can put your auth key after encrypting it on the site. Or you can simply commit the deployment out. All it does really is just deploy the release as a tag, so that it doesn't have to be done manually.

**Comment by jacobsantos** [comment]
Well, technically, as there are no unit tests, the only reason to have appveyor is to build the different versions.

**Comment by jacobsantos** [comment]
Probably going to need to write some at a later point for Enum and SafeArray. However, I'm not exactly sure how to go about writing C# test cases when it is COM. I suppose I could write a C# COM client for testing. That seems a bit more meta than I would want to do.

**Comment by mattn** [comment]
Okay, will do. Thanks for your great works.
