### ISSUE TITLE
Use VariantClear to clear VARIANT parameters passed to ole.IDispatch.Invoke

### ISSUE THREAD

**Issue by mgspross** [go-ole/go-ole#31]
After reading [this MSDN page](http://msdn.microsoft.com/en-us/library/windows/desktop/ms221165%28v=vs.85%29.aspx), I think `VariantClear` should be used to free memory used by the `VARIANT` parameters that are created in the `IDispatch.Invoke` in the library.

Currently, the `go-ole` wrapper for `IDispatch.Invoke` calls `SysFreeString` on string parameters; however, `VariantClear` seems like a more appropriate choice, since it can correctly free any `VARIANT` based on its type (i.e. it will call `SysFreeString` on strings and properly release `SAFEARRAY`'s, etc.). If I am reading the documentation correctly, it sounds like it is safe to call this function on any `VARIANT` type.

**Comment by jacobsantos** [comment]
My fork calls `VariantClear`. I will test to make sure it works correctly.

**Comment by jacobsantos** [comment]
Won't fix. VariantClear does do this, but I think for now, it might be better to leave it up to the library user. Future versions may do this.
