### ISSUE TITLE
Guide Documentation

### ISSUE THREAD

**Issue by jacobsantos** [go-ole/go-ole#50]
There are currently three ways to use the library. The OLEUtil helpers and there is a wrapper library that attempts to define a more object-oriented way of accessing COM. Finally, the procedural wrapper of shared library.

There needs to be better documentation for using the library. A guide for getting into the library other than the examples which does help, but doesn't go far enough.

What I'm thinking of is expanding the README.md to include a basic guide, then create gh-pages for a web site that includes better guide documentation for using functions and objects.

**Comment by mattn** [comment]
+1

**Comment by jacobsantos** [comment]
@mattn The documentation is coming along pretty well. I'm documenting the new version, but much of the documentation can be applied to the current version. The documentation includes examples and should be fairly complete. Which means almost every nontrivial function will have an example.

I'm not sure if I'm going to get to the `gh-pages`. That might come after appveyor and other build processes are completed. I might just build it for the `go generate` tool and leave the more guide documentation out of it for now.

I'm shooting for http://godoc.org/ viewing. I need to fix a lot of problems with the current fork, but once it is showing up, then I'll improve based on what is shown.

http://godoc.org/github.com/jacobsantos/go-com to see current progress. Some of the functions and types aren't showing up and I think that might be from compilation errors. The API has changed somewhat given the support for both cgo and shared library. I'm making some good progress, but I think I'm still several weeks away. Nothing has been tested and there will need to be a lot of testing. At least there will be documentation.

Biggest problem is trying not to plagiarize MSDN. I'm including links to many of the resources on MSDN and attempting to put a lot of the functions in my own words. I think examples would be better anyway, because who reads documentation? No one has time for that.

**Comment by mattn** [comment]
Looking good. I prefer to make documentation on godoc.org. And gh-pages should be fancy site to introduce users. :)

**Comment by jacobsantos** [comment]
I think programmers read their documentation in three ways.

 1. godoc.org
 1. readme.md (examples and other extended information)
 1. gh-pages

The documentation for godoc.org is probably the easiest, since it is part of the code and provides minimal cohesion between types and functions. Readme isn't that difficult, other than putting words together in a way that other developers can understand. I would rather take the approach of throwing enough examples at the developer that the usage seeks in over time.

GitHub Pages is probably the hardest and most time consuming. Not only does the documentation have to flow as close to a book as possible, if you want to get professional quality, it also needs context.

I think I'm going to attempt the first two and create another repository for the web site. Groups can have the web site as a separate repository and I think having the documentation site group wide is better.

Once I finish the first two, I'm going to close this ticket. I hope others continue the cause, but it is completely optional. Improvements to documentation is always wanted and needed.

**Comment by jacobsantos** [comment]
I'm going to break this out into separate tickets.
