### ISSUE TITLE
Version Number and Backwards Compatibility

### ISSUE THREAD

**Issue by jacobsantos** [go-ole/go-ole#61]
I want to introduce versions and use semantic versioning. The question is what to call the current working copy given that it is stable enough for use and what to call my fork, if it is accepted. If it is not accepted, then ignoring that and focusing on the working copy version going forward.

**Question 1: What version do we call the current working copy?**

 1. Version 0.1.0
 1. Version 1.0.0

**Question 2: Do we maintain previous versions?**

What this means is that if the next version is 1.1.x, then 1.0.x support is dropped once 1.1.0 is released. Once 2.0.0 is released, then 1.x.x support is dropped. I would suggest always accepting pull requests, but testing is usually the problem and reason why previous versions are not supported.

**Comment by jacobsantos** [comment]
**Question 1: What version do we call the current working copy?**

Version 0.1.0

Semantic versioning means that changing the API and breaking compatibility requires increasing the major version. The exception is pre-1.0 releases, which are unstable and can change on minor version increases. I think that if someone comes along and introduces a lot of changes that breaks compatibility that we don't just keep increasing the major version. The other option is forcing contributors to maintain compatibility, which can become difficult.

I know there is a stigma with working with a pre-1.0 release and working on a pre-1.0 library. Someone might look at the version and skip it not even considering that it is stable enough for use.

I will say that with my fork, I should be able to port a lot of the changes back to the current working copy and if the version is 1.0.x, then release 1.1.0 with the fork changes.

**Question 2: Do we maintain previous versions?**

I would think that this would simply be laid upon the maintainers and contributors. It is a lot of work. At some point, changes are not easily applied.

I'm concerned about supporting two versions. However, the projects that I've seen that had to work with supporting two previous versions usually burned out and dropped support for previous versions.

One notable example is WordPress, which only supports the current version and development version, even with the hundreds of contributors. The other open source projects seem to hold the same position. WordPress at one time experimented with supporting a previous release and dropped it after realizing how quickly the web application was changing.

It should be possible given that the bindings and bug fixes should be small. The problem is usually that contributors may not realize there are multiple branches and it is daunting to have to apply fixes and supply patches or pull requests for each supported branch. 

One of the primary reasons previous versions are not supported is that contributors can't be asked to provide patches for previous versions. Most contributors work towards their own requirements and if previous versions are to be supported, then those maintaining the project have to do the leg work to port the patch or pull request to previous versions, if applicable.

**Comment by mattn** [comment]
Current version is 0.1.0, And let's go to `1.0.0`. Up to `1.1.0` for minor version, up to `1.1.1` for small fixes.

**Comment by jacobsantos** [comment]
So what is the next version? 0.2 or 1.0? I would hope my fork becomes 0.2.x. I think that there are more things to do that I'm not going to be able to complete. Well, that is more, I'm not even sure how it could be completed or improved. There are enough smart people, that I'm sure improvements will come in.

**Comment by mattn** [comment]
I'm thinking go-ole is stable now. So how about to release 1.0.0 ?

**Comment by jacobsantos** [comment]
Okay. I would like to wait until the test COM Server is completed. I will create a new branch on my fork and move as much documentation and test cases over. Is that okay?

I don't want to make many code changes to the working copy, because it might make it unstable. I'm guessing you mean the current working copy as 1.0.0.

**Comment by jacobsantos** [comment]
Right, so the current working copy has been tagged 1.0.0. It might be a few more weeks or another month before my changes are completed, so I went ahead and tagged the release. It has it moments when it is quick, but writing test cases and documentation can be slow. I don't just want to just plagiarize MSDN with the documentation.

The documentation changes, guide, testing COM server and cmd generation tool will be backported as 1.1.0. If the cmd generation tool is going to be backported then it will need to add the virtual tables for the new interfaces and objects. The new code will be contained in cmd/ole (to match current go-ole naming), to contain the extra code and keep the current working copy small.

I'm not sure what the backporting will do towards the usage of either version. I suspect that those using 1.0.x or current working copy might upgrade to 1.1.x, but none of the changes will really affect them that much as most of the changes will be to support the cmd generation tool.

I'm going to use my fork for the library using COM technology. Any changes in the future will be applied to both versions, if my fork becomes 2.0.0. I will support both 1.x and 2.x with any pull requests. Until it becomes too much work.

**Comment by mattn** [comment]
How about move repository into https://github.com/go-ole ?

**Comment by jacobsantos** [comment]
okay

**Comment by mattn** [comment]
I just moved it. And how about to separate your sub-directory into several repository?

**Comment by jacobsantos** [comment]
Okay. Will do.

**Comment by jacobsantos** [comment]
I moved most of the forked code to separate packages. The COM packages (not `go-ole`) are unstable. The `com` package is now its own repo, so I'm no longer concerned about whether it will be merged. I'm still going to backport some changes and documentation and have the tools work with both `go-ole` and `com`.

I'm not sure if I should just put the rest of the COM interface packages into a single repo. I'm still thinking of whether to put the IUnknown and IDispatch in the `com` package.

There is a separate repo for the code generator tool and for the .NET COM server for testing. No work has been done for either. Well, that isn't completely true, just tiny prototype code that isn't worth committing.

**Comment by mattn** [comment]
Thanks! I will look into it.
