### ISSUE TITLE
Add support for the IEnumVARIANT dispatch interface

### ISSUE THREAD

**Issue by ahall** [go-ole/go-ole#64]
We currently have support for IDispatch, is it difficult to add support for IEnumVARIANT? See https://msdn.microsoft.com/en-us/library/windows/desktop/ms221053%28v=vs.85%29.aspx.

**Comment by jacobsantos** [comment]
You mean throughout the library, so where ever IDispatch is returned, allow for IEnumVARIANT to be returned instead?

**Comment by ahall** [comment]
In my use-case I'm calling `_NewEnum` method on a `WbemObjectSet` which returns an IEnumVARIANT and not an IDispatch interface. This lets me iterate over the WbemObjectSet. I was thinking the code would look something like this:

```
enumProxyRaw, err := oleutil.CallMethod(result, "_NewEnum")
enumProxy := enumProxyRaw.ToIEnumVARIANT()
```

Then I would call Next() on the enumProxy.

Does this make sense? I'm by no means expert on any of these :).

**Comment by mattn** [comment]
So, we can add new function to oleutil that works like below.

```
enum, err := oleutil.ToEnumVARIANT(disp)
```

**Comment by ahall** [comment]
Anyone interested in working on this, or should I try and have a go at it? :)

**Comment by jacobsantos** [comment]
@ahall It would help if you have a go at it. I think I'm going to be working on the project this week or weekend, so if you don't do a pull request, I will probably do a pull request completing this. I do want to see what your solution would be to be sure that it would be better solution or choose the better solution for merging.

**Comment by jacobsantos** [comment]
@ahall

**Comment by jacobsantos** [comment]
I wasn't able to work on this last weekend. I will try to do something this week. If you want it done faster, I will suggest a pull request.

**Comment by mattn** [comment]
I've already implemented but not tested. and still not added `oleutil.ToEnum`.

```diff
diff --git a/oleutil/oleutil.go b/oleutil/oleutil.go
index 85288f6..14337bb 100644
--- a/oleutil/oleutil.go
+++ b/oleutil/oleutil.go
@@ -130,3 +130,34 @@ func MustPutProperty(disp *ole.IDispatch, name string, params ...interface{}) (r
 	}
 	return r
 }
+
+type IEnumVARIANT struct {
+	ole.IDispatch
+}
+
+func (enum *IEnumVARIANT) Clone() (*IEnumVARIANT, error) {
+	r, err := CallMethod(enum, "Clone")
+	if err != nil {
+		return nil, err
+	}
+	return &IEnumVARIANT{*r.ToIDispatch()}, nil
+}
+
+func (enum *IEnumVARIANT) Reset() error {
+	_, err := CallMethod(enum, "Reset")
+	return err
+}
+
+func (enum *IEnumVARIANT) Skip(celt int) error {
+	_, err := CallMethod(enum, "Skip", celt)
+	return err
+}
+
+func (enum *IEnumVARIANT) Next(celt int, int q) error {
+	_, err := CallMethod(enum, "Next", celt)
+	return err
+}
```

**Comment by jacobsantos** [comment]
I guess it would make sense to just write tests for existing services until the test COM server is completed. Also, it would satisfy this ticket to test wbem service, whatever service has that object. Appveyor will probably have the service for testing.

**Comment by ahall** [comment]
This sound good guys, happy @mattn implemented this as the way I was thinking to do would have been much more complex and convoluted as I dont know the insides of go-ole as you guys do. Isn´t the hard work here pretty much done? What is left to do to here in order to raise a pull request and merge it in? :)

**Comment by jacobsantos** [comment]
@ahall I'm not sure how @mattn will implement it. Whether through pull request or directly. I think test cases will be needed at some point. If you can test it manually, it could go a long way to having it implemented.

I agree that it is simpler than what I would have done.

**Comment by jacobsantos** [comment]
Bump. Will look at this over the weekend. Need to get this in for 1.2 release.

**Comment by ahall** [comment]
Cool, keep me posted :)

**Comment by ahall** [comment]
@jacobsantos Did you get any chance to work on this yet? :)

**Comment by jacobsantos** [comment]
@ahall If you fork https://github.com/go-ole/test-com-server and add ENUM variant to the `go-ole/test-com-server`, that will go a long way to completing this.

Other than that, I'm fixing the `go-ole/test-com-server` now and will be working on getting tests into this repository using the `go-ole/test-com-server`. I'm not exactly sure how to test ENUM. I'm guessing I simply create an ENUM type or C# equiv. and pass that. Not a C# programmer and I don't know shit about how to program C#. Not too difficult though.

Not sure if it will be finished this weekend (unlikely) or sometime next week. I'm finishing the `go-ole/test-com-server` and setting up the appveyor build system for running the tests on Windows. That might take the rest of the weekend. Or a large part. I'm going to start writing tests and adding coverage. As well as the appveyor is going for the `go-ole/test-com-server`, I'm guessing the hold up is mostly going away. I just need to figure out how to get the `go-ole/test-com-server` to go-ole build process.

This is all taking place on my fork(s), so you won't be seeing that here or `go-ole/test-com-server`. At some point, when the appveyor is finished, if you fork and setup an Appveyor account, you should be able to get updates on whether it works. I'll need to talk to @mattn to get appveyor setup for `go-ole/go-ole`, since I don't appear to have permissions to do so.

If all goes well, then I want to add all of the patches and get `1.2.0` out by next weekend. Documentation can wait until the release after. I'm not sure when I'm going to be doing that. I got bored with other projects and this has been on my list of things to do. I think once `1.2.0` is out and the CI is setup, it should provide for faster releases in the future.

Sorry it has been taking so long, but I want to do this right with CI to ensure the build is as bug free as possible.

**Comment by jacobsantos** [comment]
@ahall You probably aren't worried about using tags or releases are you? In that case, it might be in sooner.

**Comment by jacobsantos** [comment]
@ahall I am almost finished with the appveyor build process. Unfortunately I'm pretty much done programming for today. Once I complete the tests are running, I'm going to hold off until tomorrow

This does mean that I will be working on it for the rest of this week. The biggest hurdle was getting the build process working. Now that is out of the way, I'm happy to do more work on this.

The tests I am going to write are going to be basic verifications of VT_Variant. I will be adding ENUM and Date to complete the other ticket that exists. Might be a day or two given how much time it has taken to work on the COM Test Server so far.

**Comment by ahall** [comment]
Excellent @jacobsantos , looking forward to it :)

**Comment by jacobsantos** [comment]
@ahall Okay, not sure if you are watching the repo, but the appveyor has been merged. That took quite a bit longer than I anticipated and I anticipated it would take a long time. Right now, only the 64-bit build and tests is working. I'm going to start writing tests tomorrow. I am thinking I will have tests for these tickets `VT_DATE` and ENUM iDispatch.

**Comment by jacobsantos** [comment]
This is implemented in #88 as *IUnknown.IEnumVARIANT()

```go
unknown, err := oleutil.CreateObject("ProgramID")
if err == nil {
    enumVARIANT, err := unknown.IEnumVARIANT()

    // Do something with enumVARIANT after checking err is nil.
}
```

**Comment by dtylman** [comment]
HI - I am trying to use this, and can't figure out a way to get this working. Trying to iterate over WMI exec query result.

The following code crashes.

Any ideas?

```go

func main(){
	defer func(){
		r:=recover()
		if r!=nil{
			fmt.Printf("%v",r)
		}
	}()
	mutex:=sync.Mutex{}
	mutex.Lock()
	defer mutex.Unlock()
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()

	err := ole.CoInitializeEx(0, ole.COINIT_APARTMENTTHREADED)
	if err != nil {
		code := err.(*ole.OleError).Code()
		fmt.Printf("CoInitializeEx returned with %v", err)
		if code == 0x00000001 { // The COM library is already initialized on this thread.

		} else {
			panic(err)
		}
	}else {
		defer ole.CoUninitialize()
	}

	comserver, err := oleutil.CreateObject("WbemScripting.SWbemLocator")
	if err != nil {
		fmt.Printf("CreateObject WbemScripting.SWbemLocator returned with %v", err)
		panic(err)
	}
	defer comserver.Release()
	dispatch,err:= comserver.QueryInterface(ole.IID_IDispatch)
	if err != nil {
		fmt.Printf("context.iunknown.QueryInterface returned with %v", err)
		panic(err)
	}
	defer dispatch.Release()
	wbemServices := oleutil.MustCallMethod(dispatch, "ConnectServer")
	defer wbemServices.Clear()
	wbemServices_dispatch:= wbemServices.ToIDispatch()
	defer wbemServices_dispatch.Release()

	objectset:= oleutil.MustCallMethod(wbemServices_dispatch,"ExecQuery","SELECT * FROM WIN32_Process")
	objectset_dispatch:=objectset.ToIDispatch()
	defer objectset.Clear()
	variant:=oleutil.MustGetProperty(objectset_dispatch,"_NewEnum")
	defer variant.Clear()
	object2:=variant.ToIUnknown()
	defer object2.Release()	
	
	//Not sure what to do here:
	enum:=ole.IEnumVARIANT{*object2}
	defer enum.Release()

	a,l,err:=enum.Next(1)
	if err!=nil{
		panic(err)
	}
	fmt.Println(&a)	
	fmt.Println(l)
}
```

Note: Trying to use ``ole.COINIT_MULTITHREADED`` results in "The application called an interface that was marshalled for a different thread"

**Comment by jacobsantos** [comment]
Please create a new ticket. In the mean time, I'm going to execute and complete the code.

Initial guess is that IEnumVARIANT is not meant to be created manually, unless you are passing that object to COM as a server.

```golang
object2 := variant.ToIUnknown().IEnumVARIANT(nil) // Does the Enum have IID or CLASSID?
defer object2.Release()

a, l, err := object2.Next(1)
```

**Comment by dtylman** [comment]
Thanks for the response.
I had no success with that. Not sure if I am mixing IEnumVariant and IEnumWbemClassObject here, 
https://msdn.microsoft.com/en-us/library/gg440854.aspx

**Comment by jacobsantos** [comment]
Look at #100 for updates.
