### ISSUE TITLE
Is there tool to display available methods and properties?

### ISSUE THREAD

**Issue by dlintw** [go-ole/go-ole#66]
Could anyone provide a helper function to display all properties and methods in an IDispatch type?

**Comment by jacobsantos** [comment]
Oh right. Well, technically that is part of the `ITypeInfo` interface. You can get a list of all names. Unfortunately that interface isn't completely implemented and the required method is one of those that are not currently implemented.

When you say, display, do you mean simply pass the list of names back or do you mean to a stream or output to a screen?

**Comment by dlintw** [comment]
I'm trying to use it, but failed.
https://github.com/go-ole/go-ole/blob/master/example/excel/excel.go
I want to know, for example,
excel, _ := unknown.QueryInterface(ole.IID_IDispatch)
workbooks := oleutil.MustGetProperty(excel, "Workbooks").ToIDispatch()

showMethodsAndProperties(excel) will get
bool Visiable
Variant Workbooks
Variant Sheets

showMethodsAndProperties(workbooks) will get
func Open(filename) (Variant , err)
func Add() (Variant , err)

Or, do you know there is other utility to know correct document about properties and methods?

**Comment by jacobsantos** [comment]
Tracking in individual tickets.
